
[package]
name = "ecode"
version = "0.1.4"
authors = ["Takasakiii <lucasmc2709@live.com>"]
edition = "2018"
license = "Public Domain"
description = "Ena Code simple Visual Studio Code profile switcher."
homepage = "https://github.com/Takasakiii/Ena-Code"
documentation = "https://github.com/Takasakiii/Ena-Code"
repository = "https://github.com/Takasakiii/Ena-Code.git"
readme = "README.md"
keywords = ["dev", "editor", "code", "profile", "switch"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.2"
