[package]
name = "ecode"
version = "0.1.0"
authors = ["Takasakiii <lucasmc2709@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "^0.8.17"
dirs = "^3.0.1"

[dependencies.serde]
version = "^1.0.125"
features = ["derive"]